name: Pages

on:
  push:
    branches:
      - main  # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install
      - name: Show node folder.
        run: ls node_modules/@bensimonds/interactive-blogging-with-observable-notebooks-and-hexo
      - name: Build
        run: yarn run build
      - name: Show build js
        run: |
          ls source/js
          ls source/js/@bensimonds
          ls source/js/@bensimonds/interactive-blogging-with-observable-notebooks-and-hexo
          ls public/js
          ls public/js/@bensimonds
          ls public/js/@bensimonds/interactive-blogging-with-observable-notebooks-and-hexo
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
